language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install poetry
install:
  - poetry install

stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script: poetry run make test
      after_script: coveralls
    - stage: deploy
      script: poetry publish -u $PYPIUSERNAME -p $PYPIPASSWORD
