language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install poetry
install:
  - poetry install

script: poetry run make test

jobs:
  include:
    if: branch = master AND tag IS present
    script: poetry publish -u $PYPIUSERNAME -p $PYPIPASSWORD
