language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - pip install poetry
install:
  - poetry install

script:
  - poetry run black --check versup
  - poetry run black --diff versup
  - poetry run make test
  - coveralls

jobs:
  include:
    - stage: deploy
      before_install: pip install poetry
      install: poetry install
      if: branch = master AND tag IS present
      script: poetry publish --build -u $PYPIUSERNAME -p $PYPIPASSWORD
