language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

jobs:
  include:
    - stage: "deploy"
      if: branch = MASTER AND tag IS present

      script:
        - echo deploy

before_install:
  - pip install poetry
install:
  - poetry install

script:
  - poetry run black --check versup
  - poetry run make test
  - coveralls
