steps:
    formatcheck:
        image: python:3.12-slim-bullseye
        when:
            event: push
        commands:
            - python -m pip install --upgrade pip
            - pip install uv
            - uv sync --all-extras --dev
            - uv run ruff format --check src
