steps:
    release:
        image: python:${TAG}-slim-bullseye
        environment:
            UV_LINK_MODE: copy
            PYPI_TOKEN:
                from_secret: pypitoken
        when:
            - event: tag
              ref: refs/tags/v*
        commands:
            - python -m pip install --upgrade pip
            - pip install uv
            - uv publish --username __token__ --password 

depends_on:
    - test

matrix:
    TAG:
        - 3.10
        - 3.11
        - 3.12

