# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [main, wf_test/**]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.27"
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: install project
        run: uv sync --all-extras --dev

      - name: Format with Ruff
        run: |
          uv run ruff format --check src

      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          uv run ruff check src
      - name: Type check with MyPy
        run: |
          # Some dependencies are missing the type definitions (semver, git)
          uv run mypy src/versup --ignore-missing-imports
      - name: Test with pytest
        run: |
          uv run pytest src/tests
      - name: Coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv run coveralls --service=github
